CREATE DATABASE #{ORACLE_SID}#
USER SYS IDENTIFIED BY #{SYS_PASS}#
USER SYSTEM IDENTIFIED BY #{SYSTEM_PASS}#
LOGFILE GROUP 1 ('/#{ORACLE_DATA}#/#{ORACLE_SID}#/redo01a.log','/#{ORACLE_DATA}#/#{ORACLE_SID}#/redo01b.log') SIZE 100M BLOCKSIZE 512,
GROUP 2 ('/#{ORACLE_DATA}#/#{ORACLE_SID}#/redo02a.log','#{ORACLE_DATA}#/#{ORACLE_SID}#/redo02b.log') SIZE 100M BLOCKSIZE 512,
GROUP 3 ('/#{ORACLE_DATA}#/#{ORACLE_SID}#/redo03a.log','/#{ORACLE_DATA}#/#{ORACLE_SID}#/redo03b.log') SIZE 100M BLOCKSIZE 512
MAXLOGHISTORY 1
MAXLOGFILES 16
MAXLOGMEMBERS 3
MAXDATAFILES 1024
CHARACTER SET AL32UTF8
NATIONAL CHARACTER SET AL16UTF16
EXTENT MANAGEMENT LOCAL
DATAFILE '/#{ORACLE_DATA}#/#{ORACLE_SID}#/system01.dbf'
SIZE 700M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED
SYSAUX DATAFILE '/#{ORACLE_DATA}#/#{ORACLE_SID}#/sysaux01.dbf'
SIZE 550M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED
DEFAULT TABLESPACE users
DATAFILE '/#{ORACLE_DATA}#/#{ORACLE_SID}#/users01.dbf'
SIZE 500M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
DEFAULT TEMPORARY TABLESPACE tempts1
TEMPFILE '/#{ORACLE_DATA}#/#{ORACLE_SID}#/temp01.dbf'
SIZE 20M REUSE AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
UNDO TABLESPACE UNDOTBS1
DATAFILE '/#{ORACLE_DATA}#/#{ORACLE_SID}#/undotbs01.dbf'
SIZE 200M REUSE AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
USER_DATA TABLESPACE usertbs
DATAFILE '/#{ORACLE_DATA}#/#{ORACLE_SID}#/usertbs01.dbf'
SIZE 200M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
